site_name: Specter DIY Documentation
site_url: https://docs.specter.solutions/diy
repo_url: https://github.com/cryptoadvance/specter-iy/
nav:
    - Home:
      - 'Introduction': README.md
      - roadmap.md
    - Hardware:
      - shopping.md
      - assembly.md
    - Software:
      - quickstart.md
      - multisig-security-tradeoffs.md
    - Development: 
      - 'Developing': development.md
      - communication.md
      - simulator.md
theme: 
  name: readthedocs